/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2018-01-07 15:13:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.business.cgd;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class receiveyycgd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/jsp/base/common_js.jsp", Long.valueOf(1514967459311L));
    _jspx_dependants.put("/WEB-INF/jsp/base/tag.jsp", Long.valueOf(1510902506752L));
    _jspx_dependants.put("/WEB-INF/jsp/base/common_css.jsp", Long.valueOf(1511161915525L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fbasename_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fbasename_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fbasename_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_fmt_005fsetBundle_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>采购产品入库</title>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseurl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("styles/style.css\"/> \r\n");
      out.write("<LINK rel=\"stylesheet\" type=\"text/css\"\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseurl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("js/easyui/themes/default/easyui.css\" />\r\n");
      out.write("<LINK rel=\"stylesheet\" type=\"text/css\"\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseurl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("js/easyui/themes/icon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"  href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseurl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("js/My97DatePicker/skin/WdatePicker.css\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseurl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("js/formvalidator/style/validator.css\"/> ");
      out.write('\r');
      out.write('\n');
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseurl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("js/jquery-1.4.4.min.js\"></script>\r\n");
      out.write("<SCRIPT type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseurl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("js/easyui/jquery.easyui.min.1.2.2.js\"></SCRIPT>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseurl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("js/easyui/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseurl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("js/jquery.form.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseurl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("js/custom.jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseurl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("js/custom.box.main.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseurl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("js/jquery.ajax.custom.extend.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<SCRIPT type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseurl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("js/menuload.js\"></SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseurl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("js/My97DatePicker/WdatePicker.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseurl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("js/jqueryvalidator/formValidator-4.1.3.js\" type=\"text/javascript\" charset=\"UTF-8\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseurl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("js/jqueryvalidator/formValidatorRegex.js\" type=\"text/javascript\" charset=\"UTF-8\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type='text/javascript' src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseurl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("dwr/engine.js'></script>   \r\n");
      out.write("<script type='text/javascript' src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseurl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("dwr/util.js'></script>  \r\n");
      out.write("<script type='text/javascript' src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseurl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("dwr/interface/dwrService.js'></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar yycgdrksubmit = function() {\r\n");
      out.write("\t\t_confirm('您确定要入库选择的产品吗?', null, function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar indexs = [];//提交记录的序号\r\n");
      out.write("\t\t\tvar rows = $('#yycgdmxlist').datagrid('getSelections');\r\n");
      out.write("\t\t\tfor (var i = 0; i < rows.length; i++) {\r\n");
      out.write("\t\t\t\tvar index = $('#yycgdmxlist').datagrid('getRowIndex', rows[i]);\r\n");
      out.write("\t\t\t\tindexs.push(index);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (rows.length > 0) {\r\n");
      out.write("\t\t\t\t$(\"#indexs\").val(indexs.join(','));\r\n");
      out.write("\t\t\t\tjquerySubByFId('yycgdrkForm', yycgdrk_callback, null);\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\talert_warn(\"请选择要入库的产品\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t};\r\n");
      out.write("\t//入库提交的回调函数\r\n");
      out.write("\tfunction yycgdrk_callback(data) {\r\n");
      out.write("\t\tvar result = getCallbackData(data);\r\n");
      out.write("\t\t_alert(result);\r\n");
      out.write("\t\tyycgdmxquery();//自动刷新本页面\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//工具栏\r\n");
      out.write("\r\n");
      out.write("\tvar toolbar = [ {\r\n");
      out.write("\t\tid : 'yycgdrksubmit',\r\n");
      out.write("\t\ttext : '确认入库',\r\n");
      out.write("\t\ticonCls : 'icon-add',\r\n");
      out.write("\t\thandler : yycgdrksubmit\r\n");
      out.write("\t} ];\r\n");
      out.write("\r\n");
      out.write("\tvar frozenColumns;\r\n");
      out.write("\r\n");
      out.write("\tvar columns = [ [\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tcheckbox : true\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'id',\r\n");
      out.write("\t\t\t\thidden : true,\r\n");
      out.write("\t\t\t\tformatter : function(value, row, index) {\r\n");
      out.write("\t\t\t\t\tif(value){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\treturn '<input type=\"hidden\" name=\"yycgdrkCustoms['+index+'].ypxxid\" value=\"'+value+'\" />';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'yycgdid',\r\n");
      out.write("\t\t\t\thidden : true,\r\n");
      out.write("\t\t\t\tformatter : function(value, row, index) {\r\n");
      out.write("\t\t\t\t\tif(value){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\treturn '<input type=\"hidden\" name=\"yycgdrkCustoms['+index+'].yycgdid\" value=\"'+row.yycgdbm+'\" />';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'useryymc',\r\n");
      out.write("\t\t\t\ttitle : '医院名称',\r\n");
      out.write("\t\t\t\twidth : 100,\r\n");
      out.write("\t\t\t\tformatter : function(value, row, index) {\r\n");
      out.write("\t\t\t\t\t//如果从json中取不出useryymc则显示成总计两个字\r\n");
      out.write("\t\t\t\t\tif (value) {\r\n");
      out.write("\t\t\t\t\t\treturn value;\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\treturn \"总计\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'yycgdbm',\r\n");
      out.write("\t\t\t\ttitle : '采购单编号',\r\n");
      out.write("\t\t\t\twidth : 80\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'yycgdmc',\r\n");
      out.write("\t\t\t\ttitle : '采购单名称',\r\n");
      out.write("\t\t\t\twidth : 200\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'cjtime',\r\n");
      out.write("\t\t\t\ttitle : '建单时间',\r\n");
      out.write("\t\t\t\twidth : 70,\r\n");
      out.write("\t\t\t\tformatter : function(value, row, index) {\r\n");
      out.write("\t\t\t\t\tif (value) {\r\n");
      out.write("\t\t\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\t\t\tvar date = new Date(value);\r\n");
      out.write("\t\t\t\t\t\t\tvar y = date.getFullYear();\r\n");
      out.write("\t\t\t\t\t\t\tvar m = date.getMonth() + 1;\r\n");
      out.write("\t\t\t\t\t\t\tvar d = date.getDate();\r\n");
      out.write("\t\t\t\t\t\t\treturn y + \"-\" + m + \"-\" + d;\r\n");
      out.write("\t\t\t\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t\t\t\t\talert(e);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'bm',\r\n");
      out.write("\t\t\t\ttitle : '流水号',\r\n");
      out.write("\t\t\t\twidth : 50\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'mc',\r\n");
      out.write("\t\t\t\ttitle : '通用名',\r\n");
      out.write("\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'jyjg',\r\n");
      out.write("\t\t\t\ttitle : '交易价',\r\n");
      out.write("\t\t\t\twidth : 40\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'cgl',\r\n");
      out.write("\t\t\t\ttitle : '采购量',\r\n");
      out.write("\t\t\t\twidth : 40\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'cgje',\r\n");
      out.write("\t\t\t\ttitle : '采购金额',\r\n");
      out.write("\t\t\t\twidth : 40\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'rkl',\r\n");
      out.write("\t\t\t\ttitle : '入库量',\r\n");
      out.write("\t\t\t\twidth : 50,\r\n");
      out.write("\t\t\t\tformatter : function(value, row, index) {\r\n");
      out.write("\t\t\t\t\tif (row.id) {\r\n");
      out.write("\t\t\t\t\t\treturn '<input type=\"text\" name=\"yycgdrkCustoms['+index+'].rkl\" />';\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\treturn value;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'rkdh',\r\n");
      out.write("\t\t\t\ttitle : '发票号或入库单号',\r\n");
      out.write("\t\t\t\twidth : 90,\r\n");
      out.write("\t\t\t\tformatter : function(value, row, index) {\r\n");
      out.write("\t\t\t\t\tif (row.id) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\treturn '<input type=\"text\" name=\"yycgdrkCustoms['+index+'].rkdh\" />';\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\treturn value;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'ypph',\r\n");
      out.write("\t\t\t\ttitle : '产品批号',\r\n");
      out.write("\t\t\t\twidth : 70,\r\n");
      out.write("\t\t\t\tformatter : function(value, row, index) {\r\n");
      out.write("\t\t\t\t\tif (row.id) {\r\n");
      out.write("\t\t\t\t\t\treturn '<input type=\"text\" name=\"yycgdrkCustoms['+index+'].ypph\" />';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\treturn value;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'ypyxq',\r\n");
      out.write("\t\t\t\ttitle : '产品有效期(年)',\r\n");
      out.write("\t\t\t\twidth : 70,\r\n");
      out.write("\t\t\t\tformatter : function(value, row, index) {\r\n");
      out.write("\t\t\t\t\tif (row.id) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\treturn '<input type=\"text\" name=\"yycgdrkCustoms['+index+'].ypyxq\"/>';\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\treturn value;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'cgztmc',\r\n");
      out.write("\t\t\t\ttitle : '采购状态',\r\n");
      out.write("\t\t\t\twidth : 60\r\n");
      out.write("\t\t\t} ] ];\r\n");
      out.write("\r\n");
      out.write("\tfunction initGrid() {\r\n");
      out.write("\t\t$('#yycgdmxlist').datagrid({\r\n");
      out.write("\t\t\ttitle : '采购单列表',\r\n");
      out.write("\t\t\t//nowrap : false,\r\n");
      out.write("\t\t\tstriped : true,\r\n");
      out.write("\t\t\t//collapsible : true,\r\n");
      out.write("\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseurl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("cgd/receiveyycgd_result.action',\r\n");
      out.write("\t\t\tqueryParams : {\r\n");
      out.write("\t\t\t\tyear : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${year}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("'\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t//sortName : 'code',\r\n");
      out.write("\t\t\t//sortOrder : 'desc',\r\n");
      out.write("\t\t\t//remoteSort : false,\r\n");
      out.write("\t\t\tidField : 'yycgdmxid',//如果值不是主键则影响获取checkbox选中个数\r\n");
      out.write("\t\t\t//frozenColumns : frozenColumns,\r\n");
      out.write("\t\t\tcolumns : columns,\r\n");
      out.write("\t\t\tautoRowHeight : true,\r\n");
      out.write("\t\t\tpagination : true,\r\n");
      out.write("\t\t\trownumbers : true,\r\n");
      out.write("\t\t\tshowFooter : true,//显示总计\r\n");
      out.write("\t\t\ttoolbar : toolbar,\r\n");
      out.write("\t\t\tloadMsg : \"\",\r\n");
      out.write("\t\t\tpageList : [ 15, 30, 50, 100 ]\r\n");
      out.write("\t\t/* ,\r\n");
      out.write("\t\t\t\tonClickRow : function(index, field, value) {\r\n");
      out.write("\t\t\t\t\t\t\t$('#yycgdmxlist').datagrid('unselectRow', index);\r\n");
      out.write("\t\t\t\t\t\t} */\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tinitGrid();\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction yycgdmxquery() {\r\n");
      out.write("\t\tvar formdata = $(\"#yycgdrkForm\").serializeJson();\r\n");
      out.write("\t\t//alert(formdata);\r\n");
      out.write("\t\t$('#yycgdmxlist').datagrid('unselectAll');\r\n");
      out.write("\t\t$('#yycgdmxlist').datagrid('load', formdata);\r\n");
      out.write("\t}\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t//dwr测试\r\n");
      out.write("\r\n");
      out.write("\t\t//没有参数的调用\r\n");
      out.write("\t\t// callback是回调方法，data是service方法返回的结果\r\n");
      out.write("\t\t/*\r\n");
      out.write("\t\t dwrService.testdwr({\r\n");
      out.write("\t\t     callback:function(data) {\r\n");
      out.write("\t\t\t     \talert(data);\r\n");
      out.write("\t\t\t     }});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tdwrService.testdwr2('zhangsan',{\r\n");
      out.write("\t\t     callback:function(data) {\r\n");
      out.write("\t\t\t     \talert(data);\r\n");
      out.write("\t\t\t     }}); \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdwrService.businessyear({\r\n");
      out.write("\t\t     callback:function(data) {\r\n");
      out.write("\t\t    \t //alert(data.length);\r\n");
      out.write("\t\t\t     \tvar i=data.length;\r\n");
      out.write("\t\t\t     \tfor(var j=0;j<i;j++){\r\n");
      out.write("\t\t\t     \t\talert(data[j].info+'   '+data[j].value);\r\n");
      out.write("\t\t\t     \t}\r\n");
      out.write("\t\t\t     }});\r\n");
      out.write("\t\t */\r\n");
      out.write("\r\n");
      out.write("\t\t//通过dwr加载年份\r\n");
      out.write("\t\t//businessyearlist('year'); \r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</HEAD>\r\n");
      out.write("<BODY>\r\n");
      out.write("\t<form id=\"yycgdrkForm\" name=\"yycgdrkForm\" method=\"post\"\r\n");
      out.write("\t\taction=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseurl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("cgd/receivesubmit.action\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"indexs\" id=\"indexs\" />\r\n");
      out.write("\t\t<TABLE class=\"table_search\">\r\n");
      out.write("\t\t\t<TBODY>\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD class=\"left\">年份(如2017)：</TD>\r\n");
      out.write("\t\t\t\t\t<td><select id=\"year\" name=\"year\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2018\">2018</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2017\">2017</option>\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t<TD class=\"left\">医院名称：</TD>\r\n");
      out.write("\t\t\t\t\t<td><INPUT type=\"text\" name=\"yycgdCustom.useryymc\" /></td>\r\n");
      out.write("\t\t\t\t\t<TD class=\"left\">采购单编号：</td>\r\n");
      out.write("\t\t\t\t\t<td><INPUT type=\"text\" name=\"yycgdCustom.bm\" /></TD>\r\n");
      out.write("\t\t\t\t\t<TD class=\"left\">采购单名称：</TD>\r\n");
      out.write("\t\t\t\t\t<td><INPUT type=\"text\" name=\"yycgdCustom.mc\" /></td>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<TD class=\"left\">采购时间：</TD>\r\n");
      out.write("\t\t\t\t\t<td><INPUT id=\"yycgdCustom.cjtime_start\"\r\n");
      out.write("\t\t\t\t\t\tname=\"yycgdCustom.cjtime_start\"\r\n");
      out.write("\t\t\t\t\t\tonfocus=\"WdatePicker({isShowWeek:false,skin:'whyGreen',dateFmt:'yyyy-MM-dd'})\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 80px\" />-- <INPUT id=\"yycgdCustom.cjtime_end\"\r\n");
      out.write("\t\t\t\t\t\tname=\"yycgdCustom.cjtime_end\"\r\n");
      out.write("\t\t\t\t\t\tonfocus=\"WdatePicker({isShowWeek:false,skin:'whyGreen',dateFmt:'yyyy-MM-dd'})\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 80px\" /></td>\r\n");
      out.write("\t\t\t\t\t<TD class=\"left\">流水号：</TD>\r\n");
      out.write("\t\t\t\t\t<td><INPUT type=\"text\" name=\"ypxxCustom.bm\" /></td>\r\n");
      out.write("\t\t\t\t\t<TD class=\"left\">通用名：</td>\r\n");
      out.write("\t\t\t\t\t<td><INPUT type=\"text\" name=\"ypxxCustom.mc\" /></TD>\r\n");
      out.write("\t\t\t\t\t<TD class=\"left\">采购状态：</td>\r\n");
      out.write("\t\t\t\t\t<td>已发货 <a id=\"btn\" href=\"#\" onclick=\"yycgdmxquery()\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-linkbutton\" iconCls='icon-search'>查询</a>\r\n");
      out.write("\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</TBODY>\r\n");
      out.write("\t\t</TABLE>\r\n");
      out.write("\r\n");
      out.write("\t\t<TABLE border=0 cellSpacing=0 cellPadding=0 width=\"99%\" align=center>\r\n");
      out.write("\t\t\t<TBODY>\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t<table id=\"yycgdmxlist\"></table>\r\n");
      out.write("\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t</TBODY>\r\n");
      out.write("\t\t</TABLE>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fsetBundle_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:setBundle
    org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag _jspx_th_fmt_005fsetBundle_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag) _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fbasename_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag.class);
    _jspx_th_fmt_005fsetBundle_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fsetBundle_005f0.setParent(null);
    // /WEB-INF/jsp/base/tag.jsp(3,0) name = basename type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fsetBundle_005f0.setBasename("resources.messages");
    // /WEB-INF/jsp/base/tag.jsp(3,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fsetBundle_005f0.setVar("messagesBundle");
    int _jspx_eval_fmt_005fsetBundle_005f0 = _jspx_th_fmt_005fsetBundle_005f0.doStartTag();
    if (_jspx_th_fmt_005fsetBundle_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fbasename_005fnobody.reuse(_jspx_th_fmt_005fsetBundle_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fbasename_005fnobody.reuse(_jspx_th_fmt_005fsetBundle_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/jsp/base/tag.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("baseurl");
    // /WEB-INF/jsp/base/tag.jsp(4,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}/", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }
}
